# Generated by Django 4.1 on 2022-08-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('from_age', models.IntegerField()),
                ('to_age', models.IntegerField()),
                ('Income_grows', models.IntegerField()),
            ],
            options={
                'db_table': 'user_data',
            },
        ),
    ]
