# Generated by Django 4.1 on 2022-08-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_userdata_income_grows_alter_userdata_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='Income_grows',
            new_name='income_grows',
        ),
    ]
